[package]
name = "party_wallet"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_party = { git = "https://github.com/misofm/party.git", rev = "72fa0c9c982166f51527d20846c2bc365b5c17f6" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "4abe4c1ff482655693698fa6ab8a6e2b58f8c635" }
vault = { git = "https://github.com/misofm/vault.git", rev = "6b55f9fe8d89f7a7974cb843b10b9827fe13ef0f", modes = ["test"] }
